#pragma once
#include <vector>
#include "enemy.hpp"
#include "star.hpp"
#include "heart.hpp"
#include "key.hpp"
#include "portal.hpp"
struct Optional_Key
{
    Key m_key;
    bool is_this_view;
};
struct Optional_Portal
{
    Portal m_portal;
    bool is_this_view;
};
struct Camera_View
{
    Optional_Key m_opt_key;
    Optional_Portal m_opt_portal;
    std::vector<Star> m_stars;
    std::vector<Enemy> m_enemies;
    std::vector<Heart> m_hearts;
};

struct View_Grid
{
    // max col and row number
    int row;
    int col;
};

struct Level
{
    int key_view;
    int portal_view;
    // number of views that have star and heart
    int number_filled_view; // from input
    // max number of star
    int max_star; // from input
    int max_heart; // from input
    int max_enemies; // from input
    // the current view pos in camera_views
    View_Grid current_view; // generated by code
    // the max col and row
    View_Grid view_grid;// from input
    std::vector<Camera_View> camera_views;
};
